{"1":{"str":"php_pinpoint"},"2":{"str":"PHPApplication"},"3":{"i64":1527751566535},"4":{"str":"ABhwaHBfcGlucG9pbnTHyduouywe"},"7":{"i64":8867794264481384357},"8":{"i64":-1},"9":{"i64":1527751586874},"10":{"i32":1},"11":{"str":"/test_recursive_exception1.php"},"12":{"i16":1500},"13":{"str":"127.0.0.1:8989"},"14":{"str":"127.0.0.1"},"15":{"lst":["rec",1,{"1":{"i32":999},"2":{"rec":{"1":{"str":"/home/liumingyi/git/pinpoint_c_agent/simulate/testcase/php/trace/test_recursive_exception1"}}}}]},"16":{"i16":0},"17":{"i32":1},"18":{"lst":["rec",3,{"7":{"i64":8867794264481384357},"8":{"i16":2},"9":{"i32":0},"10":{"i32":1},"12":{"i16":1501},"14":{"lst":["rec",1,{"1":{"i32":-1},"2":{"rec":{"1":{"str":"Array\n(\n    [0] =&gt; 0\n)\n"}}}}]},"15":{"i32":3},"16":{"i64":-1},"25":{"i32":-23},"26":{"rec":{"1":{"i32":-1},"2":{"str":"Fatal error: n < 1 in /home/liumingyi/git/pinpoint_c_agent/simulate/web/php/test_recursive_exception1.php on line 5"}}}},{"7":{"i64":8867794264481384357},"8":{"i16":1},"9":{"i32":0},"10":{"i32":1},"12":{"i16":1501},"14":{"lst":["rec",1,{"1":{"i32":-1},"2":{"rec":{"1":{"str":"Array\n(\n    [0] =&gt; 1\n)\n"}}}}]},"15":{"i32":2},"16":{"i64":-1},"25":{"i32":-23}},{"7":{"i64":8867794264481384357},"8":{"i16":0},"9":{"i32":0},"10":{"i32":1},"12":{"i16":1501},"14":{"lst":["rec",1,{"1":{"i32":-1},"2":{"rec":{"1":{"str":"Array\n(\n    [0] =&gt; 2\n)\n"}}}}]},"15":{"i32":1},"16":{"i64":-1},"25":{"i32":-23}}]},"25":{"i32":-13},"26":{"rec":{"1":{"i32":-2},"2":{"str":"Fatal error: Uncaught exception 'Exception' with message 'n < 1' in /home/liumingyi/git/pinpoint_c_agent/simulate/web/php/test_recursive_exception1.php:5\nStack trace:\n#0 /home/liumingyi/git/pinpoint_c_agent/simulate/web/php/test_recursive_exception1.php(6): test_cumsum_e1(0)\n#1 /home/liumingyi/git/pinpoint_c_agent/simulate/web/php/test_recursive_exception1.php(6): test_cumsum_e1(1)\n#2 /home/liumingyi/git/pinpoint_c_agent/simulate/web/php/test_recursive_exception1.php(9): test_cumsum_e1(2)\n#3 {main}\n  thrown in /home/liumingyi/git/pinpoint_c_agent/simulate/web/php/test_recursive_exception1.php on line 5"}}}}